services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "8080:8080" # web server port
    depends_on:
      - mqtt
    environment:
      - ROBOFLOW_API_KEY=${ROBOFLOW_API_KEY}
      - ROBOFLOW_PROJECT=${ROBOFLOW_PROJECT}
  mqtt:
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    ports:
      - "1883:1883" # mqtt port
